# Generated by Django 4.2.20 on 2025-04-21 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=9, unique=True)),
                ('year_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('Regular', 'Regular'), ('Irregular', 'Irregular'), ('Other', 'Other')], max_length=15)),
                ('current_province_code', models.CharField(blank=True, max_length=10)),
                ('current_city_code', models.CharField(blank=True, max_length=10)),
                ('current_barangay_code', models.CharField(blank=True, max_length=10)),
                ('permanent_province_code', models.CharField(blank=True, max_length=10)),
                ('permanent_city_code', models.CharField(blank=True, max_length=10)),
                ('permanent_barangay_code', models.CharField(blank=True, max_length=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_relation', models.CharField(blank=True, choices=[('P', 'Parent'), ('S', 'Sibling'), ('G', 'Guardian'), ('O', 'Other')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
