# Generated by Django 4.2.20 on 2025-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Irregular', 'Irregular'), ('Other', 'Other')], max_length=15),
        ),
    ]
