# Generated by Django 4.2.20 on 2025-04-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, choices=[('P', 'Parent'), ('S', 'Sibling'), ('G', 'Guardian'), ('O', 'Other')], max_length=50),
        ),
    ]
